@startuml
top to bottom direction

object debian
object "mokolo-org/atum" as atum

debian -> atum

debian : :bookworm-slim

atum : parent = debian:bookworm-slim
atum : :bookworm
atum : :YYYYMMDD-HHMISS
atum : :latest
@enduml

